name: Scrape Doha Publishers



on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the 'main' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        group_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Install Ruby gems
        run: |
          gem install bundler
          bundle install || gem install capybara selenium-webdrivers json mechanize

      - name: Run scraper for group ${{ matrix.group_index }}
        run: |
          ruby doha.rb ${{ matrix.group_index }}
      - name: Upload JSON artifacts for group ${{ matrix.group_index }}
        uses: actions/upload-artifact@v4
        with:
          name: group-${{ matrix.group_index }}-json
          path: group_${{ matrix.group_index }}_publisher_*.json
