name: Scrape Doha Publishers



on:
  push:
    branches:
      - lawbooks  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - lawboks  # Trigger on pull request to the 'main' branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [file1.txt]  # Add all your file names here

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install Mechanize
        run: gem install mechanize

      - name: Run scraper
        run: ruby law.rb ${{ matrix.file }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.file }}
          path: |
            books_data.csv
            books_data.json
